# -*- coding: utf-8 -*-
{
    'name': 'Job Card',
    'version': '18.0.1.0.0',
    'category': 'Job Card Management',
    'summary': 'Atlabs Job Card Management',
    'description': 'job card',
    'depends': [
        'contacts', 'fleet','product','stock','material_purchase_requisitions','hr','hr_timesheet','purchase','stock','project',
        'board','base','mail',
    ],
'data': [
    'security/ir.model.access.csv',
    'security/job_card_security.xml',
    'report/report_action.xml',
    'report/job_card_template.xml',
    'report/estimate_template.xml',
    'report/tax_invoice_template.xml',
    'report/job_card_cost_analysis_template.xml',
    'views/data.xml',
    'views/job_card_management.xml',
    'views/job_card_estimate.xml',
    'views/fleet_vehicle.xml',
    'views/res_partner.xml',
    'views/product_template.xml',
    'views/account_move.xml',
    'views/job_card_timesheet.xml',
    'views/hr_employee.xml',
    'views/job_categories.xml',
    'views/fleet_vehicle_log_contract_views.xml',
    # 'views/job_card_dashboard.xml',
    'views/cost_analysis_view.xml',
    # 'views/dynamic_report_wiz_menu.xml',
    'wizard/job_card_cost_analysis_wizard_view.xml',
    'wizard/job_card_invoice_wizard.xml',

],
    'assets': {
    'web.assets_backend': [
        'atlbs_job_card/static/src/css/custom_styles.css',
        # 'atlbs_job_card/static/src/js/job_card_dashboard.js',
    ],
    },
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}