from .import job_card_management
from .import job_card_estimate
from .import fleet_vehicle
from .import res_partner
from .import job_card_report
from .import account_move
from .import product_template
from .import job_card_timesheet
from .import hr_employee
from .import job_categories
from .import fleet_vehicle_log_contract
from .import cost_analysis_report
from .import checklist_name
from .import quality_checklist